### ISSUE TITLE
VidyoClientIOS.framework does not support Bitcode

### ISSUE THREAD

**Issue by ctnataman** [Vidyo/vidyo.io-helloworld-ios#8]
I get the following error when archiving the project. Does not the framework support bitcode? When will the framework support bitcode?

> bitcode bundle could not be generated because '<path>/vidyo.io-helloworld-ios-master/VidyoClientIOS.framework/VidyoClientIOS(VidyoConnector_Objc.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

VidyoClientIOS.framework version is 19.2.0.8

**Comment by tmelko-vidyo** [comment]
That is something that we considered in the past, but we decided against. We build our libraries without bitcode support so there is no way to provide this option at the moment. If you do decide to move forward with Vidyo, please contact us via the support system at support@vidyo.io

**Comment by ctnataman** [comment]
We already use your library in our project. We just wanted to enable bitcode to reduce the size of ipa. I sent our request via https://info.vidyo.io/vidyo-io-contact-us.html. Thank you :)
